/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.any.store.gui;

import java.awt.Color;

/**
 *
 * @author sukru
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menuPanel = new javax.swing.JPanel();
        addItemButton = new javax.swing.JButton();
        addTableButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        instrumentPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        mottoLabel = new javax.swing.JLabel();
        tableScrollPanel = new javax.swing.JScrollPane();
        tableList = new javax.swing.JList<>();
        tablePanel = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Any Store - Store anything");
        setBackground(new java.awt.Color(1, 198, 83));
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));

        menuPanel.setBackground(new java.awt.Color(99, 99, 99));
        menuPanel.setForeground(new java.awt.Color(99, 99, 99));
        menuPanel.setPreferredSize(new java.awt.Dimension(781, 50));

        addItemButton.setBackground(new java.awt.Color(99, 99, 99));
        addItemButton.setForeground(new java.awt.Color(99, 99, 99));
        addItemButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/any/store/icons/icons8_add_24px.png"))); // NOI18N
        addItemButton.setToolTipText("Add new item");
        addItemButton.setAutoscrolls(true);
        addItemButton.setContentAreaFilled(false);
        addItemButton.setFocusPainted(false);
        addItemButton.setPreferredSize(new java.awt.Dimension(27, 27));
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        addTableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/any/store/icons/icons8_add_property_26px.png"))); // NOI18N
        addTableButton.setToolTipText("Create new collection");
        addTableButton.setContentAreaFilled(false);
        addTableButton.setFocusPainted(false);
        addTableButton.setPreferredSize(new java.awt.Dimension(27, 27));
        addTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTableButtonActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/any/store/icons/icons8_edit_property_26px.png"))); // NOI18N
        jButton1.setToolTipText("Edit collection");
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(27, 27));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/any/store/icons/icons8_edit_50px_1.png"))); // NOI18N
        jButton2.setToolTipText("Edit item");
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setPreferredSize(new java.awt.Dimension(27, 27));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/any/store/icons/icons8_delete_24px.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setPreferredSize(new java.awt.Dimension(27, 27));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/any/store/icons/icons8_search_24px.png"))); // NOI18N
        jButton4.setToolTipText("Search in collection");
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setPreferredSize(new java.awt.Dimension(25, 30));

        jTextField1.setText("jTextField1");
        jTextField1.setMinimumSize(new java.awt.Dimension(64, 30));
        jTextField1.setPreferredSize(new java.awt.Dimension(190, 30));
        jTextField1.setSelectionColor(new java.awt.Color(1, 198, 83));

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(menuPanel, java.awt.BorderLayout.PAGE_START);

        instrumentPanel.setBackground(new java.awt.Color(69, 73, 74));
        instrumentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        instrumentPanel.setForeground(new java.awt.Color(69, 73, 74));
        instrumentPanel.setToolTipText("");
        instrumentPanel.setPreferredSize(new java.awt.Dimension(300, 482));
        instrumentPanel.setLayout(new java.awt.GridBagLayout());

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/any/store/icons/logo_file[313].png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 76;
        gridBagConstraints.ipady = 68;
        gridBagConstraints.weighty = 0.5;
        instrumentPanel.add(logoLabel, gridBagConstraints);

        mottoLabel.setText("Store anything");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        instrumentPanel.add(mottoLabel, gridBagConstraints);

        tableScrollPanel.setForeground(new java.awt.Color(69, 73, 74));
        tableScrollPanel.setToolTipText("");
        tableScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        tableScrollPanel.setMinimumSize(new java.awt.Dimension(150, 120));
        tableScrollPanel.setName("Collections"); // NOI18N
        tableScrollPanel.setPreferredSize(new java.awt.Dimension(150, 150));

        tableList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableList.setForeground(new java.awt.Color(255, 255, 255));
        tableList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "item 1", "item 2", "item 3", "item 4", "item 5", "item 6", "item 7", "item 8", "item 9", "item 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tableList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableList.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        tableList.setMinimumSize(new java.awt.Dimension(150, 110));
        tableList.setPreferredSize(new java.awt.Dimension(120, 150));
        tableList.setPrototypeCellValue("-----------------------"
        );
        tableList.setSelectionBackground(new java.awt.Color(1, 197, 83));
        tableList.setBackground(new java.awt.Color(69,73,74));
        tableList.setSelectionForeground(new java.awt.Color(69, 73, 74));
        tableList.setVisibleRowCount(10);
        tableScrollPanel.setViewportView(tableList);
        tableList.getAccessibleContext().setAccessibleName("");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 16;
        instrumentPanel.add(tableScrollPanel, gridBagConstraints);

        getContentPane().add(instrumentPanel, java.awt.BorderLayout.LINE_START);

        tablePanel.setBackground(new java.awt.Color(59, 59, 59));
        tablePanel.setForeground(new java.awt.Color(60, 63, 65));
        tablePanel.setLayout(new java.awt.BorderLayout());

        tableScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        tableScrollPane.setBorder(null);
        tableScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mainTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainTable.setForeground(new java.awt.Color(51, 51, 51));
        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Abasıyanık", "Sait Faik", "dsfgjhgsdf", "jhdfgbjdrf", "jdhfbgjhdfrg"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Adı", "Yazarı", "ISBN", "Konu", "null"
            }
        ));
        mainTable.setGridColor(new java.awt.Color(255, 255, 255));
        mainTable.setInheritsPopupMenu(true);
        mainTable.setRowHeight(22);
        mainTable.setSelectionBackground(new java.awt.Color(1, 198, 83));
        mainTable.setShowHorizontalLines(true);
        mainTable.getTableHeader().setReorderingAllowed(false);
        tableScrollPane.setViewportView(mainTable);

        tablePanel.add(tableScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(tablePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTableButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTableButtonActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addItemButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton addTableButton;
    private javax.swing.JPanel instrumentPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTable mainTable;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel mottoLabel;
    private javax.swing.JList<String> tableList;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JScrollPane tableScrollPanel;
    // End of variables declaration//GEN-END:variables
}
